### ISSUE TITLE
Mod incompatibilities

### ISSUE THREAD

**Issue by omegaprime02** [Roncarlos/Dimensional-Storage#2]
You asked to be informed of when there's a conflict on the mod page, so here I am.

I have managed to nail down DequeCraft (which allows you to place things at the front of the replication queue) and More_Replication (which removes 10 unit limit on the production button, allowing you to queue hundreds of items in one click) as fully incompatible (neither have any function that works while Dimensional-Storage is installed)

More_Replication throws this error when you attempt to change the number of items to replicate:
![image_2024-11-30_124705472](https://github.com/user-attachments/assets/9bd0066e-20e8-4ce9-a10d-9bf60acaa821)

DequeCraft throws this error when you attempt to engage replication:
![image_2024-11-30_124424437](https://github.com/user-attachments/assets/2d659af1-7d2e-442e-b767-82cc8852e615)

Both of these are, in my opinion, made somewhat redundant by your mod, but they are incompatible and should be looked at in case there's a deeper issue.

**Comment by Roncarlos** [comment]
DSPReplicatorPlus does the same thing and should work with my mod.

**Comment by Roncarlos** [comment]
[19160d4](https://github.com/Roncarlos/Dimensional-Storage/commit/19160d4b3c9a78ee14059be86e74e57ca5e9ad4c)
This commit fixes some problems with replication.

Also be aware that the game was updated and your mods seems to not be compatible with the new version (DSPReplicatorPlus is also impacted)
